"""Add integration system tables

Revision ID: 0ad7dc42f266
Revises: f7fd3af4bb4f
Create Date: 2025-09-21 22:38:58.172451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ad7dc42f266"
down_revision: Union[str, None] = "f7fd3af4bb4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
