"""Add workflows table

Revision ID: 5f5aa22c8e49
Revises: c594c010a2e2
Create Date: 2025-09-21 23:58:27.657427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f5aa22c8e49"
down_revision: Union[str, None] = "c594c010a2e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_configs")

    # Create workflows table
    op.create_table(
        "workflows",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False, default="pending"),
        sa.Column("steps_data", postgresql.JSON(), nullable=False, default={}),
        sa.Column("workflow_metadata", postgresql.JSON(), nullable=False, default={}),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.Column("max_parallel_steps", sa.Integer(), nullable=False, default=5),
        sa.Column("auto_retry_failed", sa.Boolean(), nullable=False, default=True),
        sa.Column("current_step_ids", postgresql.JSON(), nullable=False, default=[]),
        sa.Column("completed_step_ids", postgresql.JSON(), nullable=False, default=[]),
        sa.Column("failed_step_ids", postgresql.JSON(), nullable=False, default=[]),
        sa.Column("created_at", sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_time", sa.Integer(), nullable=True),
        sa.Column("results", postgresql.JSON(), nullable=False, default={}),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop workflows table
    op.drop_table("workflows")

    op.create_table(
        "agent_configs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_api", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("channel", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "encrypted_credentials",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "llm_provider", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ai_model", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("ai_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("max_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "temperature",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name="agent_configs_agent_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="agent_configs_pkey"),
        sa.UniqueConstraint(
            "agent_id",
            name="agent_configs_agent_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
