"""remove_agent_role_specialization_fields

Revision ID: 986bab53fb5b
Revises: fa86833dd0a6
Create Date: 2025-09-22 16:55:51.563651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "986bab53fb5b"
down_revision: Union[str, None] = "9d3995e6a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "specialization")
    op.drop_column("agents", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column("role", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agents",
        sa.Column(
            "specialization", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
