"""Add agent roles and tools support

Revision ID: 9d3995e6a5b4
Revises: f3ddab0e3a19
Create Date: 2025-09-21 22:21:06.694462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d3995e6a5b4"
down_revision: Union[str, None] = "f3ddab0e3a19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_configs")
    op.add_column("agents", sa.Column("role", sa.String(length=100), nullable=True))
    op.add_column(
        "agents", sa.Column("specialization", sa.String(length=255), nullable=True)
    )
    op.add_column("agents", sa.Column("available_tools", sa.JSON(), nullable=True))
    op.add_column("agents", sa.Column("tool_configurations", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "tool_configurations")
    op.drop_column("agents", "available_tools")
    op.drop_column("agents", "specialization")
    op.drop_column("agents", "role")
    op.create_table(
        "agent_configs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_api", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("channel", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "encrypted_credentials", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "llm_provider", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ai_model", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("ai_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("max_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "temperature",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            name="agent_configs_agent_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="agent_configs_pkey"),
        sa.UniqueConstraint(
            "agent_id",
            name="agent_configs_agent_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
