"""Update to pgvector

Revision ID: f3ddab0e3a19
Revises: initial_uuid
Create Date: 2025-09-21 19:05:57.137532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "f3ddab0e3a19"
down_revision: Union[str, None] = "initial_uuid"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Install pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Alter column type from array to vector
    op.alter_column(
        "knowledge_vectors",
        "embedding",
        existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
        type_=Vector(1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert column type from vector to array
    op.alter_column(
        "knowledge_vectors",
        "embedding",
        existing_type=Vector(1536),
        type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
