"""Add task management tables

Revision ID: f7fd3af4bb4f
Revises: 9d3995e6a5b4
Create Date: 2025-09-21 22:26:25.433155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7fd3af4bb4f"
down_revision: Union[str, None] = "9d3995e6a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
