name: Ruff CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Ruff Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        name: Ruff lint (with auto-fix)
        with:
          args: 'check --fix'

      - uses: chartboost/ruff-action@v1
        name: Ruff format
        with:
          args: 'format'
