name: Ruff CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Ruff Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.9.5

      - name: Ruff format (check only)
        run: |
          ruff format --check .

      - name: Ruff lint (all rules selected in config)
        run: |
          ruff check . --output-format=github
